### ISSUE TITLE
safari 問題

### ISSUE THREAD

**Issue by ycs77** [stephenchenorg/keebrother.nuxt3#15]
* ? 被吃掉
* 中括號連結 [] 出問題

---

有除錯的資訊就直接貼在下面

**Comment by 5SMNOONMS5** [comment]
![image](https://github.com/stephenchenorg/keebrother.nuxt3/assets/8379901/cbd49da9-bdad-4e81-86fb-e23bafad0d31)

下面這張是我把值複製出來好看板
![image](https://github.com/stephenchenorg/keebrother.nuxt3/assets/8379901/032c44d5-aaa6-4009-8955-62a553892cb5)

**Comment by 5SMNOONMS5** [comment]
確定只有 ? 被吃掉
 []  沒事，我當時應該看錯  []  部分 sor
