### ISSUE TITLE
[ 手機版 ] 產品細節頁的『相關產品』筆數要跟電腦版一樣是 4 則（左右有箭頭，可左右滑）

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#17]
![IMG_1684](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/25299a45-470f-4a5f-a2e9-910b9357825c)

**Comment by cindyvvg** [comment]
相關產品的檢視跟聯絡我們icon隱藏掉，拿首頁空間的左右箭頭來用（不透明，壓在圖上）

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
@ycs77 保留下方點點，壓在圖上的左右箭頭幫我拿掉（因為實際看了效果，覺得箭頭大，壓在上面太干擾，有點點提示可以左右滑就可以）

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
測試 ok
