### ISSUE TITLE
[ 手機版 ] 搜尋功能，會出現藍色框框

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#19]
![IMG_1681](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/45184719-9160-47d9-8188-1acc041d0eb1)

且
1. 白色底線能否調整成左右對稱？
2. 對照電腦版，少了類別的下選單

**Comment by cindyvvg** [comment]
safari
iphone 13 pro

**Comment by cindyvvg** [comment]
![IMG_EE8FCA561614-1](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/9149a0c8-dfee-4584-be24-2b3021a06a12)

**Comment by ycs77** [comment]
現在手機版改成這樣子，破版問題也解決了。

![localhost_3000_products_sort_method=desc page=2](https://github.com/stephenchenorg/keebrother.nuxt3/assets/38133356/c1012492-c715-448a-9c9b-6b12f0b9f62b)

**Comment by cindyvvg** [comment]
測試 ok
