### ISSUE TITLE
[ 手機版 ] 產品細節頁，的圖片，可否改為左右滑動的方式切換圖片（點點出現在圖片下面）

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#21]
![IMG_1683](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/5efea751-d710-4485-8e4a-31d2393eda26)

**Comment by cindyvvg** [comment]
預覽箭頭拿掉，讓麵包屑是一行字

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
@ycs77 圖片上不用再壓左右箭頭囉
![IMG_D309DDEE3C63-1](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/e50e8a93-4e90-47f9-ba7b-cbfad0a304c5)

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
測試 ok
