### ISSUE TITLE
[ 手機版 ]關於我們 banner 那邊的標題，字可以小一些嗎？那目前內容是一排

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#22]
![IMG_1AC73BE8F454-1](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/7df6a5fa-f3d4-42e9-bd88-30b15f663a02)

**Comment by cindyvvg** [comment]
只要是手機裝置，都強制是等比縮放

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
測試 ok
