### ISSUE TITLE
[ 手機版 ] 結果筆數那行字，跟排序功能的字，可以對齊嗎

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#23]
![IMG_F6BFE3019265-1](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/a1a4c2be-7a27-4b7d-b58c-001c2b00ced0)

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
測試 ok
