### ISSUE TITLE
關於我們的小圖，改為 optional

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#24]
<img width="1570" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/a50f6e59-3ddc-4f9a-bda0-e48e8940954a">

**Comment by cindyvvg** [comment]
@ycs77 
現在小圖如果有上圖，前端會變這樣
<img width="1666" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/981244b9-7690-4a63-86c8-fb34c2799512">

**Comment by cindyvvg** [comment]
@5SMNOONMS5 麻煩幫我把圖拿掉
<img width="560" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/85c8c200-7eb2-4452-8434-ed89e74ad077">

**Comment by ycs77** [comment]
小圖是要這樣的嗎?

![1702656742518](https://github.com/stephenchenorg/keebrother.nuxt3/assets/38133356/a8ddfebd-17b1-4787-91c0-5c22b4e28202)

**Comment by cindyvvg** [comment]
@ycs77 
是這樣
<img width="1669" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/c31afb3e-9f1f-4f18-8735-90bf67f21b49">

**Comment by cindyvvg** [comment]
抱歉，是我的問題，我自己忘記原圖比例了，所以上了一張錯的尺寸
我剛剛上了320*400的圖就沒問題了！
我把單關掉
