### ISSUE TITLE
產品底層頁，下面的 4 個頁籤，若有 Tab 沒上資料，該 Tab 隱藏

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#25]
- Device: iOS / Android / Windows 11
- Browser: Chrome / Safari

<img width="930" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/a30698bf-fa1f-46c8-872d-833bc1249d33">

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
『詳細規格』跟『規格說明（圖文編輯器）』是在同一個 Tab，要兩個資料都沒上，該 Tab 才會隱藏唷

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
測試 ok
