### ISSUE TITLE
品牌情境圖 CTA 按鈕，後台有上連結，點了沒作用

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#26]
- Device: iOS / Android / Windows 11
- Browser: Chrome / Safari

<img width="1452" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/9446646f-cd71-4251-b160-37f1431529ad">

<img width="1710" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/44ba6871-0f20-422a-b673-f2ca7496f49b">

**Comment by ycs77** [comment]
已修復

**Comment by cindyvvg** [comment]
測試 ok
