### ISSUE TITLE
品牌底層頁，介紹文字後台上了，前台出不來

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#27]
- Device: iOS / Android / Windows 11
- Browser: Chrome / Safari

後台有上資料
![image](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/8103f087-db7f-49f8-9ecb-801b1deba71b)

前台沒有顯示
![image](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/0bec1fac-b982-415e-aec5-0f9224d19756)

**Comment by ycs77** [comment]
有喔！是正常的

https://staging-keebrother.netlify.app/brands/2
