### ISSUE TITLE
品牌底層頁面點擊索取型錄 以及 官網好像沒有接到 api 的值，都會默認點到 Lamp

### ISSUE THREAD

**Issue by 5SMNOONMS5** [stephenchenorg/keebrother.nuxt3#28]
- Browser: Chrome  120.0.6099.109

api 確認都有傳不同值

![Screen Shot 2023-12-19 at 2 42 02 PM](https://github.com/stephenchenorg/keebrother.nuxt3/assets/8379901/4a51952c-c7d6-42da-9d05-ccadbbfd7abf)

**Comment by ycs77** [comment]
done
