### ISSUE TITLE
聯絡我們的 Banner 協助換圖

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#30]
聯絡我們的 Banner 當時說寫死，後台不開欄位，但可以幫忙換一下圖嗎？之後不會再更動
![image](https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/8c553ac6-a947-444b-97ac-cef3b75e757d)

**Comment by ycs77** [comment]
換好了👍

**Comment by cindyvvg** [comment]
測試 ok
