### ISSUE TITLE
電腦版-文章彈跳視窗的切換點點要有點擊功能

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#31]
- Device: iOS / Android / Windows 11
- Browser: Chrome / Safari

目前文章的彈跳視窗，再多張圖片的狀況下，是拖曳圖片來切換圖片沒問題
<img width="1710" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/de6f1ef9-d902-453b-9683-ddd706e0ccbe">
但是，但是，圖片下方的切換點點，要加上選取圖片的功能，即：
點第一個點點，切到第一張圖
點第二個點點，切到第二張圖
點第三個點點，切到第三張圖

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
測試 ok
