### ISSUE TITLE
手機版-右側的廣告區塊尺寸與排列

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#33]
- Device: iOS / Android / Windows 11
- Browser: Chrome / Safari

目前手機版多則廣告是直接向下排列，應依照 Figma，
1. 拖曳圖片左右切換，
2. 且下方有點點，點擊第幾個點點，切換到第幾張圖
3. 廣告圖片長寬大小依照 Figma
<img width="410" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/345e20a7-d43e-471b-ba4b-8b4810f300ac">

目前的手機版廣告為向下排列，無法左右切換，且長寬尺寸跟 Figma 不同
<img width="193" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/150913be-c2e0-4830-bf51-46df0489fba8">

**Comment by ycs77** [comment]
done

**Comment by cindyvvg** [comment]
測試 ok
