### ISSUE TITLE
右側的廣告區塊，第一則顯示不出來

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#35]
- Device: iOS / Android / Windows 11
- Browser: Chrome / Safari

<img width="1708" alt="Screenshot 2023-12-29 at 11 34 52 PM" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/0c025865-a527-4914-8ede-f5820fa28f2d">

**Comment by ycs77** [comment]
這是後端 API 問題，API 那張給的圖片路徑是 `https://staging-file.encoredays.com/`，當然不會正常顯示。

**Comment by cindyvvg** [comment]
ok
