### ISSUE TITLE
產品列表頁面圖片如果是空值 要呈現 default 圖

### ISSUE THREAD

**Issue by 5SMNOONMS5** [stephenchenorg/keebrother.nuxt3#40]
- Device: iOS / Android / Windows 11
- Browser: Chrome / Safari

<img width="400" alt="product_image_default" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/8379901/5827b519-176f-4d7c-8ff2-fa0024a0bd5e">

**Comment by ycs77** [comment]
done
