### ISSUE TITLE
產品詳情頁的型錄 Tab ，點擊 download 按鈕，檔案都無法下載成功

### ISSUE THREAD

**Issue by cindyvvg** [stephenchenorg/keebrother.nuxt3#41]
- Device: iOS / Android / Windows 11
- Browser: Chrome / Safari
https://staging-keebrother.netlify.app/products/5839

會出現這個錯誤訊息
<img width="375" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/264409af-d7fa-4cf1-a226-eb69f08af94d">

**Comment by ycs77** [comment]
修好了

**Comment by cindyvvg** [comment]
目前點 download 出現
<img width="1607" alt="image" src="https://github.com/stephenchenorg/keebrother.nuxt3/assets/98463232/84e90f27-af5a-4612-8bbe-3dbe00a6e81d">

**Comment by ycs77** [comment]
@5SMNOONMS5 已處理完成
